name: Fetch RSS Feed
permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # every day at 06:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install feedparser requests

      - name: Fetch feed and update CSV
        run: python scripts/fetch_feed.py

      - name: Create GitHub issues for new items
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/create_issues.py

      - name: Commit CSV updates
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/items.csv
          git diff --staged --quiet || git commit -m 'chore: update RSS feed items'

      - name: Push changes
        run: git push
