name: Policy Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,8,16 * * *'

permissions:
  contents: write
  issues: write
  models: read # allow workflows to access models

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install -g playwright
          playwright install --with-deps chromium

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch RSS feed
        run: python scripts/fetch_feed.py

      - name: Create issues with screenshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/create_issues_with_screenshots.py

      - name: Run grok diff and comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/grok-diff.py

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/items.csv data/issue_map.json grok-diff.md README.md
          git diff --staged --quiet || git commit -m 'chore: update policy data and analysis'

      - name: Push changes
        run: git push

