name: XML Diff Narrative Summary (HuggingFace)

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/**/*.xml'

jobs:
  xml-diff-narrative:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Find pairs and summarize XML differences
        run: python scripts/xml_diff_narrative.py

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: xml-diff-narratives
          path: xml_diff_narratives.json
