name: XML Diff Narrative Summary (HuggingFace)

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/**/*.xml'

jobs:
  xml-diff-narrative:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install lxml transformers torch

      - name: Find XML pairs with matching names except date
        id: find_pairs
        run: |
          import os, re, json
          from collections import defaultdict

          pattern = re.compile(r"^(.*?)(\d{4}-\d{2}-\d{2})\.xml$")
          files = defaultdict(list)
          for root, dirs, filenames in os.walk('data'):
              for f in filenames:
                  if f.endswith('.xml'):
                      m = pattern.match(f)
                      if m:
                          prefix = os.path.join(root, m.group(1))
                          files[prefix].append(os.path.join(root, f))

          pairs = []
          for prefix, flist in files.items():
              if len(flist) >= 2:
                  # sort files by date in filename (descending)
                  flist.sort(reverse=True)
                  for i in range(len(flist)-1):
                      pairs.append([flist[i], flist[i+1]])

          with open("pairs.json", "w") as out:
              json.dump(pairs, out)
          print(f"::set-output name=pairs::{json.dumps(pairs)}")
        shell: python3

      - name: Summarize XML file differences using HuggingFace Transformers
        if: steps.find_pairs.outputs.pairs != '[]'
        run: |
          import json, difflib, os
          from lxml import etree
          from transformers import pipeline

          pairs = json.load(open("pairs.json"))
          output = []

          summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")

          def xml_diff_summary(file1, file2):
              with open(file1, 'r') as f1, open(file2, 'r') as f2:
                  xml1 = etree.tostring(etree.parse(f1), pretty_print=True).decode()
                  xml2 = etree.tostring(etree.parse(f2), pretty_print=True).decode()
              diff = list(difflib.unified_diff(
                  xml1.splitlines(), xml2.splitlines(),
                  fromfile=os.path.basename(file1),
                  tofile=os.path.basename(file2),
                  lineterm=''
              ))
              diff_text = "\n".join(diff)
              preamble = (
                  f"Here is a diff between two XML files. Briefly summarize the key differences in plain language for a non-technical reader:\n"
              )
              input_text = preamble + diff_text
              # HuggingFace models have a limit on input length, so we truncate if necessary
              input_text = input_text[:1024]
              summary = summarizer(input_text, max_length=120, min_length=30, do_sample=False)[0]['summary_text']
              return summary

          for file1, file2 in pairs:
              summary = xml_diff_summary(file1, file2)
              output.append({
                  "file1": file1,
                  "file2": file2,
                  "summary": summary
              })

          with open("xml_diff_narratives.json", "w") as out:
              json.dump(output, out, indent=2)

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: xml-diff-narratives
          path: xml_diff_narratives.json
